#-------------------------------
# General Site Settings
title: Jiyoon's Devlog
logo: none.svg # You can add own logo. #ë¡œê³  ì—†ìœ¼ë©´ titleì´ ë‚˜ì˜´
description: 


#-------------------------------
# Author Settings
author:
  name: Jiyoon Kim
  image: none.jpg
  say-hello: G'day! Iâ€™m <strong>ì§€ìœ¤(Jiyoon)</strong>.
  bio: XR developer who just graduated with an anthropology degree. Aspires to be part of creating a world, striving to make it a good one.ğŸ˜‰ Based in Seoul, South Korea.

#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
#JY ì•„ë˜ SNS ì•„ì´ì½˜ í•„ìš”
youtube: https://youtube.com/
brunch: https://brunch.com/

facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
